In [2]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [3]:
#rivising everything till date

In [4]:
#things that numpy provide are
#ndarray--> a fast multidimensional array for vectorized mathematics,
#standard mathematical functions for fast array calculations without having to write loops
#• ndarray, a fast and space-efficient multidimensional array providing vectorizedarithmetic operations and sophisticated broadcasting capabilities
# Standard mathematical functions for fast operations on entire arrays of datawithout having to write loops
# Tools for reading / writing array data to disk and working with memory-mappedfiles
# Linear algebra, random number generation, and Fourier transform capabilities
# Tools for integrating code written in C, C++, and Fortran

In [5]:
#ndarray
x=np.array([1,23.4,5.6,])

In [6]:
x

array([  1. ,  23.4,   5.6])

In [7]:
x.shape #columns ,rows

(3L,)

In [8]:
x.size #total elements

3

In [9]:
x.ndim #dimensions

1

In [10]:
x*10

array([  10.,  234.,   56.])

In [11]:
x+x

array([  2. ,  46.8,  11.2])

In [12]:
x*x

array([   1.  ,  547.56,   31.36])

In [13]:
x//x

array([ 1.,  1.,  1.])

In [14]:
x**2

array([   1.  ,  547.56,   31.36])

In [15]:
np.zeros((2,3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [16]:
np.zeros_like(x)

array([ 0.,  0.,  0.])

In [17]:
#similar is ones and ones_like

In [18]:
np.eye(2)#or np.identity makes an identity matrix

array([[ 1.,  0.],
       [ 0.,  1.]])

In [19]:
#we can assign the data types 
y=np.array([2,4,5,5],dtype=np.float64)

In [20]:
type(y)

numpy.ndarray

In [21]:
y.dtype

dtype('float64')

In [22]:
new_y=y.astype(np.int)

In [23]:
new_y

array([2, 4, 5, 5])

In [24]:
new_y.dtype

dtype('int32')

In [25]:
#similarily you can convert the string into float type

In [26]:
#basic indexing and slicing
new_y


array([2, 4, 5, 5])

In [27]:
new_y[2:4]

array([5, 5])

In [28]:
new_y[2:4]=143


In [29]:
new_y


array([  2,   4, 143, 143])

In [30]:
'''An important first distinction
from lists is that array slices are views on the original array. This means that
the data is not copied, and any modifications to the view will be reflected in the source
array'''

'An important first distinction\nfrom lists is that array slices are views on the original array. This means that\nthe data is not copied, and any modifications to the view will be reflected in the source\narray'

In [31]:
deepak=np.array([4,35,6.6,6,88,43,"deepak"])

In [32]:
deepak 

array(['4', '35', '6.6', '6', '88', '43', 'deepak'], 
      dtype='|S32')

In [33]:
# for two dimensional arrays 
one=np.arange(12).reshape(4,3)

In [34]:
one

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [35]:
one[2][0] 

6

In [36]:
#or
one[2,0]

6

In [37]:
one.T

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [38]:
one.T.dot(one)

array([[126, 144, 162],
       [144, 166, 188],
       [162, 188, 214]])

In [39]:
#or 
np.dot(one,one.T)

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [40]:
one.dot(one.T)

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

In [41]:
#the swapaxes key word takes no.of axes and swap them up


In [42]:
#universal functions


In [43]:
a=np.arange(15)

In [44]:
np.sqrt(a)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739])

In [45]:
np.exp(a)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04,   5.98741417e+04,
         1.62754791e+05,   4.42413392e+05,   1.20260428e+06])

In [46]:
'''it has all kind of functions like for subtraction,addition,power ,maximum and minimum elements of two arrays etc'''

'it has all kind of functions like for subtraction,addition,power ,maximum and minimum elements of two arrays etc'

In [47]:
#conditional logic np.where(this array if true,select from this,else from this)
from_this=np.array([True,False,True,False,True,False])
selct_this=np.random.random(6)
or_this=np.random.random(6)

In [48]:
now=np.where(from_this,selct_this,or_this)

In [49]:
now

array([ 0.13392444,  0.32404759,  0.49273538,  0.39344973,  0.89363001,
        0.19306581])

In [50]:
an=np.random.random_integers(0,15,15).reshape(5,3)

In [51]:
an

array([[ 9,  0,  2],
       [ 9, 11,  7],
       [ 6, 13, 11],
       [11,  4, 13],
       [ 2,  3,  0]])

In [52]:
an.std()#std dev

4.4790872085975533

In [53]:
an.sum()

101

In [54]:
an.mean(axis=1)

array([  3.66666667,   9.        ,  10.        ,   9.33333333,   1.66666667])

In [55]:
an.cumsum(0) #see adding row wise

array([[ 9,  0,  2],
       [18, 11,  9],
       [24, 24, 20],
       [35, 28, 33],
       [37, 31, 33]])

In [56]:
an.cumsum(1) #column wise similarily cumprod

array([[ 9,  9, 11],
       [ 9, 20, 27],
       [ 6, 19, 30],
       [11, 15, 28],
       [ 2,  5,  5]])

In [57]:
#others are std->for std deviation,var->for variance ,min,max,argmin,argmax->gives the indices of minimum and maximum

In [58]:
#methods for boolean array
arr=np.random.randn(100)
arr

array([-0.66012076, -0.68057992,  0.28903175, -0.64573377, -0.92746216,
        0.43338802,  1.75947821,  0.68041541, -0.5561438 , -0.42082322,
        0.18365845,  0.97185286,  1.12937022,  0.18765511,  0.53052002,
        1.2101124 , -1.49268068,  0.57864817,  0.06021521,  0.24402613,
       -2.0067613 ,  0.44268123,  1.18117211,  0.34673121,  1.21265133,
       -0.35212291,  0.0073351 ,  0.37847047, -0.85152957,  1.66778424,
       -0.88358112, -0.28420588,  1.57217277, -1.73637395, -1.66691695,
       -1.14048633, -2.04801735, -1.81383402,  0.72035551,  1.12616403,
        0.4677278 , -1.59832965, -1.17923707, -0.83579059,  0.18519599,
        0.02396823, -0.68283562,  1.45950828, -0.84926173, -1.67902176,
        0.9461904 , -1.06539737,  0.49747439,  1.27294008,  1.14189256,
       -0.00930679, -1.65405827,  0.89499061,  1.14831716, -1.37640011,
       -1.40713996,  2.49897979,  0.36285485,  0.50487772, -1.09232972,
        0.96742343, -2.5566616 , -0.8326953 ,  0.8341315 , -0.87

In [59]:
(arr>0)

array([False, False,  True, False, False,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True, False,  True,  True,  True,  True, False,  True,
        True, False,  True, False, False,  True, False, False, False,
       False, False,  True,  True,  True, False, False, False,  True,
        True, False,  True, False, False,  True, False,  True,  True,
        True, False, False,  True,  True, False, False,  True,  True,
        True, False,  True, False, False,  True, False, False,  True,
       False,  True, False,  True, False, False,  True, False, False,
        True, False,  True, False,  True, False, False,  True,  True,
       False, False, False,  True, False,  True, False, False,  True,  True], dtype=bool)

In [60]:
#now in order to count the total no.of true
(arr>0).sum()

51

In [61]:
#arr.any->return if any element is true and arr.all ->returns boolean true if all the values are true

In [62]:
np.array([False,True,True,]).all()

False

In [63]:
#sorting

#unique keyword
#gives unique elements

see=np.array(["deepak","kumar","deepak","raj","singh","kumar"])
np.unique(see)

array(['deepak', 'kumar', 'raj', 'singh'], 
      dtype='|S6')

In [64]:
#or we can do by this way
set(see)

{'deepak', 'kumar', 'raj', 'singh'}

In [65]:
np.sort(set(see))

array(set(['deepak', 'kumar', 'singh', 'raj']), dtype=object)

In [66]:
#other set methods are intersect1d,union1d,setdiff1d,setxor1d

In [69]:
a=[]
for x in range(10):
    a=1 if np.random.random_integers(0,1) else -1
    print a
    
    

-1
-1
1
-1
-1
-1
1
-1
1
1


In [74]:
np.random.random_sample((3,2)) #random sample return samples from open interval [0.0 to 1.0) 

array([[ 0.99905281,  0.75931319],
       [ 0.09434043,  0.6287145 ],
       [ 0.9176398 ,  0.79251347]])

In [2]:
#and the parameters denote the shape of the matrix
